In [9]:
import numpy as np
import os
import pandas as pd

In [3]:
base_path = '/mnt/disk1/heonseok/MPMLD/data/location'
dataset = np.load(os.path.join(base_path, 'data_complete.npz'))

In [7]:
# print(dataset)
x_data=dataset['x'][:,:]
y_data=dataset['y'][:]

print(x_data)
print(x_data.shape)
print(y_data)
print(y_data.shape)



[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
(5010, 446)
[13 11  3 ... 10 20  4]
(5010,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [10]:
df = pd.DataFrame(x_data)
print(df.describe())

               0            1            2            3            4    \
count  5010.000000  5010.000000  5010.000000  5010.000000  5010.000000   
mean      0.058283     0.178044     0.047904     0.537325     0.092814   
std       0.234302     0.382588     0.213585     0.498655     0.290201   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     1.000000     0.000000   
75%       0.000000     0.000000     0.000000     1.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               5            6            7            8            9    ...  \
count  5010.000000  5010.000000  5010.000000  5010.000000  5010.000000  ...   
mean      0.107385     0.030938     0.058283     0.161277     0.064271  ...   
std       0.309633     0.173167     0.234302     0.367823     0.245260  ...   
min       0.00000

In [12]:
print(np.unique(y_data))
print(len(np.unique(y_data)))



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
30


In [13]:
y_data = y_data - 1
print(np.unique(y_data))
print(len(np.unique(y_data)))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
30


In [15]:
y_data_small = y_data[0:1000]
print(np.unique(y_data_small))
print(len(np.unique(y_data_small)))
print(y_data_small)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
30
[12 10  2  8  7  2 19 10 18 26 12 28  3 29 25 13 10  0 22 20  5 10 15 27
  7  4  9 19 16 20  7 24 18 29 11 25 22 17  1 25 18  2 23 16 19  0  4 19
 17 12 29 27 14 12  8 28 14 22  2  6 11 27 14 23 16  3 12 29  8 19  3 26
 12 18 19 27 29 18  7  0 14 21 19 14 22 14 13 10  0 29 29 22 15 26 20  1
 12 10  3 27  5 26  7  0 19  1 13 22 23 27 29  7 23 29 13 13  8 20  1  1
 28  3 19  7 11 19  8  3  6 23 23  2 27 28  7 20 23 20 18 24 22 28 28  1
 20 28  2 11 14 29 26  2  0  2  7 11 21 17 19  7  5 13 25  8 18 20 25 20
 13  7 20 10  9 23  7 24 21  4  0 19  9 18 11  6 16 20 25  2  9 12 26 12
  3 22 14  2 27  2 14 23 22 15 10  5 16 19  8  8  7 20 18  7 20  7 12 19
  4 18 26 26 28  4 22 29  9 10 13 28 19  4 19 20  9  0  0 26 28 28 19 10
 27  8 16 29 25 21  9  4 12  3  6 14  6 25 19 17 27 19 12  7 14  5  7 26
 28 22 27 22 20 16 25 21  9 14 21 14 23 19 27 22  5 26 19 29  6 15 11  2
  7  2 23 15 25 10 27 19 14 

In [17]:
for i in range(len(np.unique(y_data))):
    print(i, np.sum(y_data == i))


0 169
1 178
2 147
3 155
4 97
5 182
6 120
7 308
8 145
9 210
10 189
11 184
12 141
13 122
14 229
15 110
16 176
17 128
18 180
19 254
20 228
21 117
22 158
23 170
24 139
25 139
26 155
27 152
28 149
29 179


In [18]:

for i in range(len(np.unique(y_data_small))):
    print(i, np.sum(y_data_small == i))




0 26
1 28
2 36
3 29
4 20
5 40
6 22
7 71
8 24
9 44
10 34
11 30
12 30
13 28
14 47
15 21
16 33
17 30
18 33
19 55
20 48
21 28
22 30
23 38
24 20
25 23
26 34
27 35
28 30
29 33
